### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by metscore** [fadden/DynamicScriptSandbox#4]
Hi,

I've had much help from this library when trying to create my own "plugin system", but there is one thing that I haven't really grasped.
Plugins, that are used in my program, must be based on a base class from an assembly which I provide. This base class assembly contains some housekeeping functions to make sure the plugin adheres to specific rules. This works well, but since the user (in my application) can dynamically specify the plug-in path I need to provide this base class assembly in the plug-in folder, but this means that my base class assembly is going to be in all the plug-in folders that the user might have. This has obvious drawbacks if I need to update the base class assembly.
I’d like the line
PluginLoader pl = (PluginLoader)mAppDomain.CreateInstanceAndUnwrap(typeof(PluginLoader).Assembly.FullName, typeof(PluginLoader).FullName);
to look in another folder (such as my application install folder) for the base class assembly upon trying to access the PluginLoader.
I might have missed if this is possible or even feasible, but any small tip on how to direct the assembly load from a different location would be greatly appreciated.

King regards
Magnus

**Comment by fadden** [comment]
I think you'd need to leave the `AppDomainSetup.ApplicationBase` set to the location of your base class assembly, and then add a `FileIOPermission` for the additional directory, and have the remote side load the assembly from the other directory.  So add a second path argument to `DomainManager`'s constructor, and modify `CreateDomain()` to set up the second path.  `PluginLoader` is taking a full path to the dll, so that shouldn't need to change.

([My app](https://github.com/fadden/6502bench) copies DLLs around, but the plugins are always placed in a subdirectory of the install dir, so this isn't too onerous.)

AppDomains don't always behave the way I expect though. :-(  Case in point: last week I [fixed a bug](https://github.com/fadden/6502bench/commit/195c93a94ad9de4484ccb951cd3463ad560d68ec) in my app that caused it to crash if you let the computer suspend for a few minutes.  When the computer wakes up, if the remote objects have passed their expiration date, they all get discarded.  (I should update the README here to mention this.)

**Comment by metscore** [comment]
Thank you fadden for your quick response.

Your answer seems like a good starting point for going forward with this issue. 
I'll try to pursue your suggestion to see if I manage to pull it off!

Again, your comment is appreciated!
